name: Deploy Contoso_University_Core

on:
  workflow_run:
    workflows: ["Pack Contoso_University_Core"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    environment: production
    steps:
      - name: Print name
        run: echo "${{env.TENANT_ID}}""
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pack-solution.yml
          name: packed-solution
      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: https://org56bc8f2e.crm11.dynamics.com/
#          user-name: ${{ secrets.USERNAME }}
#          password-secret: ${{ secrets.PASSWORD }}
          app-id: ${{env.CLIENT_ID}}
          client-secret: ${{secrets.DEPLOY_SECRET}}
          tenant-id: ${{env.TENANT_ID}}
          solution-file: contoso_university_core_managed.zip

