name: Deploy Contoso_University_Core

on:
  workflow_run:
    workflows: ["Pack Contoso_University_Core"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    environment: production
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pack-solution.yml
          name: packed-solution
      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: https://org56bc8f2e.crm11.dynamics.com/
#          user-name: ${{ secrets.USERNAME }}
#          password-secret: ${{ secrets.PASSWORD }}
          app-id: 9ce436bb-5517-4acd-a4c7-77ef1887f459
          client-secret: KqK8Q~xKOiovaRFr7FoanVd4NGF_2Rf7VtCLxaKj
          tenant-id: 98a52d09-d007-4f9a-b05f-d825a5750996
          solution-file: contoso_university_core_managed.zip

