name: Export Contoso_University_Core

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    environment: production
    steps:
      - uses: microsoft/powerplatform-actions/export-solution@v0
        with:
            environment-url: https://org56bc8f2e.crm11.dynamics.com/
            app-id: ${{ vars.CLIENT_ID }}
            client-secret: ${{ secrets.DEPLOY_SECRET }}
            tenant-id: ${{ vars.TENANT_ID }}
            solution-name: 'contoso_university_core'
            solution-output-file: '/out/contoso_university_core_Managed.zip'
            managed: true
            # working-directory: 'out'

