name: Export Contoso_University_Core

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: microsoft/powerplatform-actions/export-solution@v0
        with:
            environment-url: https://org56bc8f2e.crm11.dynamics.com/
            app-id: ${{ vars.CLIENT_ID }}
            client-secret: ${{ secrets.DEPLOY_SECRET }}
            tenant-id: ${{ vars.TENANT_ID }}
            solution-name: 'Contoso University - Core'
            solution-output-file: 'contoso_university_core.zip'
            working-directory: 'out'

